apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: nginx-deployment
  namespace: dev
spec: 
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1 
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels: 
         app: webapp
    spec:
      containers:
        - name: nginx 
          image: eswararavind/docker:${DOCKER_TAG}
          ports:
            - containerPort: 80 
               
